-- file=道具.xlsx[道具] key=
TableGoodsConfig = {
[1]={["id"]=1,["goodId"]=1,["goodName"]="金币",["goodType"]=2,["goodDesc"]="金币",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={},["price"]=1},
[2]={["id"]=2,["goodId"]=2,["goodName"]="1元话费券",["goodType"]=1,["goodDesc"]="可兑换话费",["goodIcon"]="lb_package_phoneTicket_png",["isShow"]=1,["useType"]="PhoneFeesCharge",["giftGoods"]={},["price"]=0},
[3]={["id"]=3,["goodId"]=3,["goodName"]="10000金币",["goodType"]=4,["goodDesc"]="10000金币",["goodIcon"]="lb_turntable_BigGold_png",["isShow"]=0,["useType"]="",["giftGoods"]={},["price"]=0},
[4]={["id"]=4,["goodId"]=4,["goodName"]="喇叭",["goodType"]=1,["goodDesc"]="可发送全服公告",["goodIcon"]="lb_package_laba_png",["isShow"]=0,["useType"]="",["giftGoods"]={},["price"]=0},
[5]={["id"]=5,["goodId"]=5,["goodName"]="奖券",["goodType"]=3,["goodDesc"]="奖券",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={},["price"]=0},
[6]={["id"]=6,["goodId"]=6,["goodName"]="喇叭礼包",["goodType"]=4,["goodDesc"]="喇叭礼包",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=4,["goodNum"]=10},{["goodId"]=1,["goodNum"]=6000}},["price"]=0},
[7]={["id"]=7,["goodId"]=7,["goodName"]="转盘券",["goodType"]=1,["goodDesc"]="转盘券",["goodIcon"]="lb_package_zhuanpanTicket_png",["isShow"]=1,["useType"]="",["giftGoods"]={},["price"]=0},
[8]={["id"]=8,["goodId"]=8,["goodName"]="转盘券礼包",["goodType"]=4,["goodDesc"]="转盘券礼包",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=7,["goodNum"]=10},{["goodId"]=1,["goodNum"]=3000}},["price"]=0},
[9]={["id"]=9,["goodId"]=9,["goodName"]="首充礼包",["goodType"]=4,["goodDesc"]="首充礼包",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=2,["goodNum"]=1},{["goodId"]=1,["goodNum"]=2000},{["goodId"]=7,["goodNum"]=3},{["goodId"]=4,["goodNum"]=1}},["price"]=0},
[10]={["id"]=10,["goodId"]=10,["goodName"]="16G优盘",["goodType"]=5,["goodDesc"]="16G优盘",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={},["price"]=0},
[11]={["id"]=11,["goodId"]=11,["goodName"]="无线鼠标",["goodType"]=5,["goodDesc"]="无线鼠标",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={},["price"]=0},
[12]={["id"]=12,["goodId"]=12,["goodName"]="移动电源",["goodType"]=5,["goodDesc"]="移动电源",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={},["price"]=0},
[13]={["id"]=13,["goodId"]=13,["goodName"]="ZIP打火机",["goodType"]=5,["goodDesc"]="ZIP打火机",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={},["price"]=0},
[14]={["id"]=14,["goodId"]=14,["goodName"]="10金币",["goodType"]=4,["goodDesc"]="10金币",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=1,["goodNum"]=10}},["price"]=0},
[15]={["id"]=15,["goodId"]=15,["goodName"]="60000金币",["goodType"]=4,["goodDesc"]="60000金币",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=1,["goodNum"]=60000}},["price"]=0},
[16]={["id"]=16,["goodId"]=16,["goodName"]="120000金币",["goodType"]=4,["goodDesc"]="120000金币",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=1,["goodNum"]=120000}},["price"]=0},
[17]={["id"]=17,["goodId"]=17,["goodName"]="300000金币",["goodType"]=4,["goodDesc"]="300000金币",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=1,["goodNum"]=300000}},["price"]=0},
[18]={["id"]=18,["goodId"]=18,["goodName"]="500000金币",["goodType"]=4,["goodDesc"]="500000金币",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=1,["goodNum"]=500000}},["price"]=0},
[19]={["id"]=19,["goodId"]=19,["goodName"]="1080000金币",["goodType"]=4,["goodDesc"]="1080000金币",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=1,["goodNum"]=1080000}},["price"]=0},
[20]={["id"]=20,["goodId"]=20,["goodName"]="4880000金币",["goodType"]=4,["goodDesc"]="4880000金币",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=1,["goodNum"]=4880000}},["price"]=0},
[21]={["id"]=21,["goodId"]=21,["goodName"]="9980000金币",["goodType"]=4,["goodDesc"]="9980000金币",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=1,["goodNum"]=9980000}},["price"]=0},
[22]={["id"]=22,["goodId"]=22,["goodName"]="49980000金币",["goodType"]=4,["goodDesc"]="49980000金币",["goodIcon"]="",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=1,["goodNum"]=49980000}},["price"]=0},
[23]={["id"]=23,["goodId"]=23,["goodName"]="5元话费券",["goodType"]=4,["goodDesc"]="5元话费券",["goodIcon"]="lb_package_phoneTicket5_png",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=2,["goodNum"]=5}},["price"]=0},
[24]={["id"]=24,["goodId"]=24,["goodName"]="50元话费券",["goodType"]=4,["goodDesc"]="50元话费券",["goodIcon"]="lb_package_phoneTicket50_png",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=2,["goodNum"]=50}},["price"]=0},
[25]={["id"]=25,["goodId"]=25,["goodName"]="100元话费券",["goodType"]=4,["goodDesc"]="100元话费券",["goodIcon"]="lb_package_phoneTicket100_png",["isShow"]=0,["useType"]="",["giftGoods"]={{["goodId"]=2,["goodNum"]=100}},["price"]=0},
}
